### ISSUE TITLE
RWLS not working

### ISSUE THREAD

**Issue by stephoog** [LLNL/LEAP#10]
Hey! RWLS reconstruction returns all zeros. Could you look into this?

**Comment by kylechampley** [comment]
It would be helpful to have a little more information about this error.  Could you send me the following:
1) The screen output of leapct.print_parameters()
2) The source of the data
3) The scaling of the data (min/ max) values
4) Do any of the other reconstruction algorithms return an expected result?

**Comment by stephoog** [comment]
The data is simulated medical CT. Yes FBP and LS reconstructions looks good. My screen output:
RWLS iteration 1 of 10
        lambda = 0.0
invalid step size; quitting!

**Comment by kylechampley** [comment]
OK, well, then, it must be that the weights are messing things up.  It would be helpful if you sent me the output of leapct.print_parameters().  In any case, make sure the detector pixel sizes and reconstruction voxel sizes are specified in mm.

If you are simulating by forward projecting a voxelized volume, make sure the units of the voxel values are in mm^-1.  Water should be around 0.02.  If you see values above 1000, these are in Hounsfield units and need to be scaled by 1/50000 to put them in approximate mm^-1 units.

Here is why this matters.  If the values in the volume are too high, then the values in the forward simulation will be too high and then weights in RWLS are set to exp(-g) by default and exp(-LARGE) = 0.  So this will zero out everything.  Remember this is a quantitative algorithm that requires that the weights model the noise in the data, so if it is off, the reconstruction won't work.

**Comment by stephoog** [comment]
That did it thanks!
