### ISSUE TITLE
centerRow  param does not work?

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#101]
Even I change the centerRow parameter in leap class , it does not work effectively, I can not see any change in volume center shift. Normally, it make the z-slice center shift in volume image. Please check this point at modular beam mode.

**Comment by kylechampley** [comment]
What geometry are you using?  Note that centerRow is not a modular-beam parameter.  For modular-beam data, use the [shift_detector](https://leapct.readthedocs.io/en/latest/ctgeometries.html#leapctype.tomographicModels.shift_detector) function.

**Comment by winguphehe** [comment]
The column shift is more often. In my case, the centerCol takes No effect. I use the tau parameter to handle column shift instead.

**Comment by kylechampley** [comment]
It has no effect?!  It definitely does have an effect, so it makes me think you are using it incorrectly.  Definitely don't use tau instead of centerCol.  These are different parameters for different things.  Sure, tau can be used to effectively shift the detector, but it also implicitly rotates the detector.  Can you send me a sample script to demonstrate your issue?

**Comment by hws203** [comment]
My meaning of no work on centerRow  is as like below sequence for regeneration.

1. leapct->set_centerCol(leapct->params.centerCol+ offx);
 1-1. Leap->params.convert_conebeam_to_modularbeam();
 1-2. then offx works on volume image, and I can see volume image change.
2. leapct->set_centerRow(leapct->params.centerRow+ offy);
 2-1. Leap->params.convert_conebeam_to_modularbeam();
 2-2. then offy does not work on volume image, and I can not see any volume image change.

3. offx, offy is pixel unit for example 10,10.

**Comment by hws203** [comment]
Yes, tau is effective now, I reported this tau issue a few days ago. You can see it at closed issue list.

**Comment by hws203** [comment]
Yes, I can assure that centerRow is working at leatct package by checking your above test script. The issue is just too small pixel value(10) of centerRow at my own c++ package, because I used too small pixelwith of detector for ct magnification.  I will close this issue.
