### ISSUE TITLE
demo example fbp reconstruction error

### ISSUE THREAD

**Issue by spencer03172023** [LLNL/LEAP#102]
Dear Mr Kyle Champley,

While running all demo examples which has fbp reconsturction, below error happen, have you ever met it?
"Failed to plan 1d r2c fftFailed to plan 1d r2c fft (size 1024)".

By the way, I did use the projection/back-projection of your package before, and it work well.

Thanks

**Comment by kylechampley** [comment]
I have not seen an issue like that for at least 4-6 months.

My best guess is that you've ran out of memory on your GPU.  Can you check your GPU memory usage?  LEAP does check GPU memory usage and it tries not to allocate more memory than is available.

Could you let me know which LEAP version you are running.

**Comment by kylechampley** [comment]
It looks like I fixed that bug I was speaking about in version 1.12.  Regardless, I would update LEAP to the most current version.  I always maintain backward compatibility, so upgrading shouldn't affect you negatively.  The newer version have resolved more bug fixes and have many speed and accuracy improvements, so it is worth it to upgrade.

Are you using the precompiled LEAP library or did you compile it yourself?  This issue could be related to the fact that LEAP requires cufft and your computer either does not have this library or it uses a version that is incompatible with the version I used to compile LEAP.  Thus it may be useful to try to recompile LEAP on your computer and/or update the version of cufft.

**Comment by spencer03172023** [comment]
> It looks like I fixed that bug I was speaking about in version 1.12. Regardless, I would update LEAP to the most current version. I always maintain backward compatibility, so upgrading shouldn't affect you negatively. The newer version have resolved more bug fixes and have many speed and accuracy improvements, so it is worth it to upgrade.
> 
> Are you using the precompiled LEAP library or did you compile it yourself? This issue could be related to the fact that LEAP requires cufft and your computer either does not have this library or it uses a version that is incompatible with the version I used to compile LEAP. Thus it may be useful to try to recompile LEAP on your computer and/or update the version of cufft.

Thanks, Kyle.
I did compile it myself, I will check if cufft exist and try to recompile LEAP.

**Comment by kylechampley** [comment]
Any luck resolving this issue?

**Comment by spencer03172023** [comment]
> Any luck resolving this issue?

Thanks, seems something wrong with my conda env. I did re-install it without conda env, it can work. Thanks
