### ISSUE TITLE
MAR supporting at conebeam

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#105]
@champley Can you guide me how to adapt leapct"s MAR into conebeam? Your demo script only supports at fanbeam case.

**Comment by hws203** [comment]
Yes, I can see your demo script works well at the case of more than one row value. So it is for cone-beam. Thanks for your confirmation.

**Comment by kylechampley** [comment]
The most time-consuming part of this algorithm is generating the "prior" sinogram using RWLS.  Note that this can be generated with a low-resolution reconstruction to save time.  I tested this with the demo script and not only did it run faster, but it gave better results!

**Comment by hws203** [comment]
@kylechampley Thanks for your comments. I will do it too.

**Comment by hws203** [comment]
I reconstructed some limited range of z-slice(50) from real sample projection images, then which saves some time. I guess that the metal size is limited, and it will not affect all z-slice area.  Below is the slice from real sample.
![chicken](https://github.com/user-attachments/assets/f7666075-e1ed-4ece-82ea-a0cfe75bac73)

**Comment by kylechampley** [comment]
There are definitely parameters to tune in this algorithm.  Make sure the entire metal region is segmented out- you may want to dilate your segmentation to include the boundary.  Your prior image must be artifact-free.  I'd definitely use a lot of iterations of RWLS and use a volume that is downsampled by a factor between 2 and 4.  You may also want to modify the weights in RWLS.

**Comment by hws203** [comment]
I used the dilate function at metal mask image, then I can see a little better one.

![chicken_3](https://github.com/user-attachments/assets/217e1d9d-b29f-4f3f-89b7-3896d63dfae1)
