### ISSUE TITLE
FBPscalar

### ISSUE THREAD

**Issue by zhangr05** [LLNL/LEAP#108]
Hi, Kyle 

Thank you, this is a great contribution to the CT community.

I have a question regarding the FBP reconstruction. Based on the document:
"FBP function can be achieved by running the following functions:
filterProjections(f)
weightedBackproject(g,f)
f *= get_FBPscalar()"

However, when I replace the FBP with the above (e.g., in d01_standard_geometries.py), the intensity values are off by a lot. I wonder if there is a bug somewhere.

**Comment by kylechampley** [comment]
Oh, sorry about that.  That is not quite correct.  The code below should be used.  Would you tell me where I wrote that so I can fix it?  Thanks.
```
leapct.filterProjections(g)
leapct.weightedBackproject(g,f)
```
Note that the argument to filterProjections is "g" and NOT "f".

**Comment by zhangr05** [comment]
Kyle, thanks for the quick response!

There are a few places on this page: https://leapct.readthedocs.io/en/latest/fbp.html#leapctype.tomographicModels.weightedBackproject 

For example:
leapctype.tomographicModels.filterProjections
leapctype.tomographicModels.weightedBackproject (which notes: "Don’t forget to scale your reconstruction by get_FBPscalar() to obtain a quantitatively accurate result.")

**Comment by kylechampley** [comment]
Thanks, I revised those statements which will go out in the next release.

I'm going to close this issue, but feel free to re-open it if something else comes up.
