### ISSUE TITLE
offsetScan not working?

### ISSUE THREAD

**Issue by hyaihjq** [LLNL/LEAP#11]

**Comment by kylechampley** [comment]
It seems to work for the situations that I've tested.  Did you find a case where it did not work as expected?  If so, please provide more detail.

**Comment by hyaihjq** [comment]
First of all, I would like to express my sincere gratitude to open-source for such a powerful algorithm library.
I have successfully reconstructed the correct image. After offsetscan function cropping, how to remove a circle of beam edges around the image? Thank you！
![image](https://github.com/LLNL/LEAP/assets/27874026/d494da7d-1930-486d-a5da-0ed6d8deb3e4)
![image](https://github.com/LLNL/LEAP/assets/27874026/2b59bff3-e445-48fe-bf3a-339fd936b256)
Tree shaped stripes appear in the upper part of the image.
![image](https://github.com/LLNL/LEAP/assets/27874026/cb57b755-2171-4d08-81d6-b181dbc51194)

**Comment by kylechampley** [comment]
You're welcome and we hope many people find LEAP useful.  If you find LEAP helpful, then please "star" the repo and be sure to site us if you publish work that uses LEAP.

I am concerned that you said you "cropped" your data.  You should not need to crop the data to perform an offset scan.  In fact, you should keep all good data.

Anyway, to remove the circular mask, just increase the field of view.  Just this command:
leapct.set_diameterFOV(d),
where d is the diameter of the circular mask measured in mm.  If you know this only needs to be increase by, say, 10 voxels, you can do this:
leapct.set_diameterFOV((10+leapct.get_numX())*leapct.get_voxelWidth())

Let me know if this solves your issue.
