### ISSUE TITLE
auto selection of energy value for BHC

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#110]
@kchampley  I can see that your energy value on your BHC demo script is 63.9544 with H2O. Because your phantom shows  0.02 mm^-1  LAC. But I wonder that how to get the correct this energy value from my own projection image.  Could you give me some guide or adapt any algorithm into leapct to get best value from only normalized projection images ?

**Comment by kylechampley** [comment]
You can choose any value of referenceEnergy you wish.  For single material BHC, this parameter only effects the scaling of the result, but regardless of the value, the beam hardening artifacts will be removed.  If you wish to choose a value where the beam hardening artifacts are removed, but the scaling is not changed very much, then you can use the [effectiveEnergy](https://xrayphysics.readthedocs.io/en/latest/utility.html#xrayphysics.xrayPhysics.effectiveEnergy) function and choose the material and mean thickness of your sample.  Other popular choices are the mean energy of the spectra or the "thin film" effective energy, where you use a thickness of zero in the effectiveEnergy function.

**Comment by hws203** [comment]
Thanks for your comments, I will check it and close this issue soon.

**Comment by hws203** [comment]
As you said, regardless of reference energy value, BHC algorithm's effect is valid. But my sample is not single material, so the result is not so good for me. I will close this issue.
