### ISSUE TITLE
question about RDLS

### ISSUE THREAD

**Issue by stefenmax** [LLNL/LEAP#112]
Hi. I came across the Regularized Derivative Least Squares (RDLS) reconstruction algorithm described in the [documentation](https://leapct.readthedocs.io/en/latest/iterative_reconstruction.html#leapctype.tomographicModels.RDLS), but I couldn’t find the reference or original literature for this method. Could you please provide the relevant citation or point me to the original paper or source that details this algorithm? Especially for the derivative part.

Thank you for your help!

**Comment by kylechampley** [comment]
Ya, RDLS is something that is a part of my unpublished work.  I am working on a publication, but I'm not sure it'll ever get done.  I'm just too busy.  Anyway, here is a screenshot from a part of that unpublished paper.  Let me know if you need more detail.
![image](https://github.com/user-attachments/assets/62574780-9656-4cb0-8d5f-b0c858bc31a2)

**Comment by stefenmax** [comment]
Thanks for sharing! Recently, I discovered that RDLS performs better than ASD-POCS in my project, which integrates a diffusion model to address limited-angle CT reconstruction. I’m planning to write more about the technical details of how RDLS works, but since it's unpublished, I’m unsure how to proceed with handling that. lol

**Comment by kylechampley** [comment]
I went ahead and published the full paper on [arXiv](https://arxiv.org/abs/2410.07552).  It has a more thorough description of RDLS and other novel feature in LEAP, so you may want to give it a read.  If you use RDLS, please cite the LEAP paper and this new preprint.  Thanks.

**Comment by stefenmax** [comment]
Thanks for your effort. Really appreciate it!! Definately will cite your papers.
