### ISSUE TITLE
Bug report on modularBeamBackprojectorKernel_eSF()   function

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#114]
@kchampley I can see that your modularBeamBackprojectorKernel_eSF() function works different from modularBeamBackprojectorKernel_SF() and the result  of  modularBeamBackprojectorKernel_eSF() makes only all blank slice as like below.
Please check this  modularBeamBackprojectorKernel_eSF().

![blank](https://github.com/user-attachments/assets/3cbdd9ec-2434-491e-b4b1-caad7d25fd95)

**Comment by hws203** [comment]
I am using temporary solution to make params->voxelSizeWorksForFastSF() return true always. So the doFBP() always uses the modularBeamBackprojectorKernel_SF() function. Then there is no such issue.

**Comment by kylechampley** [comment]
I did test it and everything seems to be working fine.  Thus it seems that there must be something special about the particular geometry that you are using.  Would you mind sending me a script that recreates this issue?

**Comment by kylechampley** [comment]
BTW, please do not use (at)kchampley.  Notice that my correspondence is always with @kylechampley.  Thanks.

**Comment by hws203** [comment]
For your regeneration of this issue, I made a test script by python code, but this python code does not make this issue. All looks good.  Maybe it is related to my own native c++ base code. I will check it more.
