### ISSUE TITLE
Laminograph mode default FOV  setting ? 

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#115]
@kylechampley As you can see below, your leapct shows  a circle type slice which looks different from left one. I used two different recon engines, one is leapct(right side) and the other one(left side), and it shows differrent FOV on slice image.
If we use laminography mode, then leapct makes a default circle FOV?  Is there any method to make leapct show full rectangle slice?
![lami_circle](https://github.com/user-attachments/assets/68d10810-5ac0-4460-914d-02b5e0372da7)

**Comment by kylechampley** [comment]
Ya, just use the following function: [set_diameterFOV](https://leapct.readthedocs.io/en/latest/ctvolume.html#leapctype.tomographicModels.set_diameterFOV).

If you never want to see this circular mask, you can just set this to a really big number, like 1.0e16.

**Comment by hws203** [comment]
Thanks. it works.
