### ISSUE TITLE
The results of the python program and the C++ program in the FBP algorithm are inconsistent

### ISSUE THREAD

**Issue by Y7NINE** [LLNL/LEAP#120]
python reconstructed images are smooth and C++ reconstructed images have a lot of ring artifacts. Is that the step in python that calls mean processing
![image](https://github.com/user-attachments/assets/16637b09-0454-4f86-a8b5-fbcf568399e6)
![image](https://github.com/user-attachments/assets/86a54fa1-245c-4255-b0b6-948694b42085)
![image](https://github.com/user-attachments/assets/c2065364-0ac5-43ab-bd5c-a01165910fc2)

**Comment by kylechampley** [comment]
When I remember seeing your Python script, you did not provide the air scan image.  If you use the same air scan image in both, they will look similar.

Yes, the flux correction can be helpful, but it does not affect those ring artifacts.

**Comment by Y7NINE** [comment]
https://drive.google.com/file/d/1McaHp96NDRYJvrKwkP-lw-Q42X0zH8GY/view?usp=sharingI 
provided the same projection and air, is there a difference in the dual flight on your computer? I am the person you solved the C++ interface for me before, and the data connection is the same URL as before
![屏幕截图 2024-10-18 221625](https://github.com/user-attachments/assets/6ad85274-1ff2-485d-b882-6a9b3d1f5e31)

**Comment by kylechampley** [comment]
Yes, I definitely remember you and this issue.  Unfortunately, I don't think I can help much more.  We've identified that there are some small differences in the Python and C++ methods, and these must be rectified before they both produce the same result.  

I'm here to answer any questions you have about LEAP and am willing to help with a little troubleshooting, but I must establish some boundaries, or I'll have no life.

**Comment by Y7NINE** [comment]
Thank you very much for your guidance! On this issue has been very embarrassed! Then I'll close the question

**Comment by Y7NINE** [comment]
@kylechampley Thanks for your advice and inspiration. I found the problem and solved it. My reason is that there is a difference between the normalization part of C++ and python, which leads to ring artifacts
First of all, I saved the result of this function in the python function and ran it in the C++ program, which solved the problem perfectly
![image](https://github.com/user-attachments/assets/ac3d0142-1a01-4642-aa49-11a2f8903257)
![image](https://github.com/user-attachments/assets/c512bfa4-c961-455d-96bc-5e35f6859c7a)
![image](https://github.com/user-attachments/assets/fc0f3e05-0ad0-484d-bd25-4af8ad80721d)

**Comment by Y7NINE** [comment]
I use the OPENCV library implements makeAttenuationRadiographs c + + version
Here is my c++ code that I am happy to share
#include <stdio.h>   // For file operations and printf
#include <stdlib.h>  // For malloc and free
#include <iostream>  // For std::cout (if needed)

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include "opencv2/core/cuda.hpp"
#include "opencv2/imgproc.hpp"
using namespace cv;
using namespace std;

int main()
{
    float* proj = NULL; // Object projection data
    float* proj_empty = NULL; // Air projection data
    int ns = 1328;
    int nt = 1024;
    int na = 800;
    const char* fname_out = "Half-fanFDK-leap-.raw"; // Reconstructed image file
    FILE* fid = NULL;
    int wh = ns * nt;
    
    //--------------------read air and object projection----------------------
    //+++++++++++air projection+++++++++++
    proj_empty = (float*)malloc(sizeof(float) * ns * nt); // Air projection data
    printf("Start to read air projection!\n");
    const char* proj_file_2 = { "air90.raw" }; // Full-Fan
    fid = fopen(proj_file_2, "rb");
    if (fid == NULL) { 
        printf("\nERROR: Could not open pre-weight file %s\n", proj_file_2); 
    }
    fread(proj_empty, sizeof(float), ns * nt, fid);
    fclose(fid);
    printf("Reading air projection is done!\n");

    //++++++++++++object projection+++++++++++++
    proj = (float*)malloc(sizeof(float) * ns * nt * na); // Object projection data
    printf("Start to read object projection!\n");
    const char* proj_file_1 = { "proj-42-841.raw" }; // Full-Fan
    fid = fopen(proj_file_1, "rb");
    if (fid == NULL) { 
        printf("\nERROR: Could not open pre-weight file %s\n", proj_file_1); 
    }
    fread(proj, sizeof(float), ns * nt * na, fid);
    fclose(fid);
    printf("Reading object projection is done!\n");

    // Define ROI
    int ROI[4] = {30, 80, 950, 1000}; 
    // Store mean results
    vector<float> postageStamp(800);
    Mat projALL(na, wh, CV_32FC1);
    
    #pragma omp parallel for 
    for (int i = 0; i < na; i++)  // Loop over angles 
    {
        cout << i << endl;
        // Copy one page
        Mat proj_i = Mat(nt, ns, CV_32FC1, proj + i * wh);
        
        // Convert proj_empty to Mat type
        Mat air(nt, ns, CV_32FC1, proj_empty);

        Mat result;
        divide(proj_i, air, result); // Divide the current page by the air projection
        
        // Define ROI region
        Rect roi(ROI[2], ROI[0], ROI[3] - ROI[2] + 1, ROI[1] - ROI[0] + 1);

        // Calculate mean of the ROI
        Scalar meanValue = mean(result(roi));
        postageStamp[i] = meanValue[0]; // Take the first element of the mean

        result = result.reshape(1, 1).clone(); // Clone to ensure safety

        result.copyTo(projALL.row(i));
    }

    #pragma omp parallel for 
    // Process the first 800 rows for normalization
    for (int i = 0; i < 800; i++) {
        // Get the mean value of the current row
        float meanValue = postageStamp[i]; // Directly retrieve mean
        // Normalize the current row
        projALL.row(i) /= meanValue;  // Divide by mean
        log(projALL.row(i), projALL.row(i)); // Add a small constant to avoid log(0)
        projALL.row(i) *= -1.0; // Multiply by -1
    }

    // Convert Mat to 1D float array
    int totalSize = projALL.total(); // Get the total number of elements
    float* projArray = new float[totalSize]; // Dynamically allocate memory

    // Copy data to 1D array
    memcpy(projArray, projALL.data, sizeof(float) * totalSize);

    FILE* file3 = fopen("projlogC++.raw", "wb");
    fwrite(projArray, sizeof(float), ns * nt * na, file3);
    fclose(file3);

    system("pause");
    return 0;
}

**Comment by leekunpeng** [comment]
> I use the OPENCV library implements makeAttenuationRadiographs c + + version我使用 OPENCV 库实现 makeAttenuationRadiographs c + + 版本 Here is my c++ code that I am happy to share这是我很高兴分享的 c++ 代码 #include <stdio.h> // For file operations and printf#include <stdio.h> // 用于文件操作和 printf #include <stdlib.h> // For malloc and free#include <stdlib.h> // 对于 malloc 和 free #include // For std::cout (if needed)#include // 对于 std：：cout （如果需要）
> 
> #include <opencv2/core.hpp> #include <opencv2/imgproc.hpp> #include "opencv2/core/cuda.hpp"#include “opencv2/core/cuda.hpp” #include "opencv2/imgproc.hpp"#include “opencv2/imgproc.hpp” using namespace cv; 使用 namespace cv; using namespace std; 使用 namespace std;
> 
> int main() int main（） { float* proj = NULL; // Object projection data浮点数* proj = NULL;对象投影数据 float* proj_empty = NULL; // Air projection data浮点数* proj_empty = NULL;空气投影数据 int ns = 1328; int nt = 1024; 国际 nt = 1024; int na = 800; 国际 na = 800; const char* fname_out = "Half-fanFDK-leap-.raw"; // Reconstructed image fileconst char* fname_out = “Half-fanFDK-leap-.raw”;重建的图像文件 FILE* fid = NULL; 文件* fid = NULL; int wh = ns * nt;
> 
> ```
> //--------------------read air and object projection----------------------
> //+++++++++++air projection+++++++++++
> proj_empty = (float*)malloc(sizeof(float) * ns * nt); // Air projection data
> printf("Start to read air projection!\n");
> const char* proj_file_2 = { "air90.raw" }; // Full-Fan
> fid = fopen(proj_file_2, "rb");
> if (fid == NULL) { 
>     printf("\nERROR: Could not open pre-weight file %s\n", proj_file_2); 
> }
> fread(proj_empty, sizeof(float), ns * nt, fid);
> fclose(fid);
> printf("Reading air projection is done!\n");
> 
> //++++++++++++object projection+++++++++++++
> proj = (float*)malloc(sizeof(float) * ns * nt * na); // Object projection data
> printf("Start to read object projection!\n");
> const char* proj_file_1 = { "proj-42-841.raw" }; // Full-Fan
> fid = fopen(proj_file_1, "rb");
> if (fid == NULL) { 
>     printf("\nERROR: Could not open pre-weight file %s\n", proj_file_1); 
> }
> fread(proj, sizeof(float), ns * nt * na, fid);
> fclose(fid);
> printf("Reading object projection is done!\n");
> 
> // Define ROI
> int ROI[4] = {30, 80, 950, 1000}; 
> // Store mean results
> vector<float> postageStamp(800);
> Mat projALL(na, wh, CV_32FC1);
> 
> #pragma omp parallel for 
> for (int i = 0; i < na; i++)  // Loop over angles 
> {
>     cout << i << endl;
>     // Copy one page
>     Mat proj_i = Mat(nt, ns, CV_32FC1, proj + i * wh);
>     
>     // Convert proj_empty to Mat type
>     Mat air(nt, ns, CV_32FC1, proj_empty);
> 
>     Mat result;
>     divide(proj_i, air, result); // Divide the current page by the air projection
>     
>     // Define ROI region
>     Rect roi(ROI[2], ROI[0], ROI[3] - ROI[2] + 1, ROI[1] - ROI[0] + 1);
> 
>     // Calculate mean of the ROI
>     Scalar meanValue = mean(result(roi));
>     postageStamp[i] = meanValue[0]; // Take the first element of the mean
> 
>     result = result.reshape(1, 1).clone(); // Clone to ensure safety
> 
>     result.copyTo(projALL.row(i));
> }
> 
> #pragma omp parallel for 
> // Process the first 800 rows for normalization
> for (int i = 0; i < 800; i++) {
>     // Get the mean value of the current row
>     float meanValue = postageStamp[i]; // Directly retrieve mean
>     // Normalize the current row
>     projALL.row(i) /= meanValue;  // Divide by mean
>     log(projALL.row(i), projALL.row(i)); // Add a small constant to avoid log(0)
>     projALL.row(i) *= -1.0; // Multiply by -1
> }
> 
> // Convert Mat to 1D float array
> int totalSize = projALL.total(); // Get the total number of elements
> float* projArray = new float[totalSize]; // Dynamically allocate memory
> 
> // Copy data to 1D array
> memcpy(projArray, projALL.data, sizeof(float) * totalSize);
> 
> FILE* file3 = fopen("projlogC++.raw", "wb");
> fwrite(projArray, sizeof(float), ns * nt * na, file3);
> fclose(file3);
> 
> system("pause");
> return 0;
> ```
> 
> }
```
//pProj: proj data
//pAir: air data
//result: data
for (size_t i = 0; i < na; i++)
{
  for (size_t j = 0; j < nt*ns; j++)
  {
    result[i * nt * ns + j] = = log(pProj[i * nt * ns + j] / pAir[j] + 1); 
  } 
}
```

**Comment by leekunpeng** [comment]
> Thank you very much for your guidance! On this issue has been very embarrassed! Then I'll close the question

Don't feel embarrassed. Beginners will always run into problems with simple basics.
