### ISSUE TITLE
Question: Spectral calibration

### ISSUE THREAD

**Issue by ProjX0** [LLNL/LEAP#122]
@kylechampley  d37_spectral_calibration.py script, and I have a couple of questions regarding the detector configuration.

detResp = physics.detectorResponse('GOS', None, 0.1, Es)

I noticed that the detector material is set to 'GOS'. I would like to modify this material to something like 'CdTe', but when I attempt this change, I encounter an error. Could you kindly advise on the correct way to specify different detector materials in this context?

Additionally, I am interested in performing energy-bin-specific calibration for a photon counting detector. Is such calibration possible with this framework? If so, could you please provide guidance on how to implement it?
Thank you

**Comment by kylechampley** [comment]
Yes, you can replace GOS with CdTe, but where it says "None" you must enter the mass density of the scintillator.

I don't understand you second question about calibration for a photon counting detector.  Can you elaborate?

**Comment by ProjX0** [comment]
I will try entering the scintillator density as you suggested.

Regarding the second question, may I refer you to a paper for further explanation?
(Sidky, Emil Y., et al. "Spectral calibration of photon‐counting detectors at high photon flux." Medical Physics 49.10 (2022): 6368-6383.)

**Comment by kylechampley** [comment]
Honestly, I don't have a lot of experience with photon counting detectors, so I can't offer much advise.

**Comment by ProjX0** [comment]
Thank you for your honest reply.
I've confirmed that it works well after adding the mass density of the scintillator.
I appreciate your help!

you can close this issue.

**Comment by kylechampley** [comment]
OK, best of luck!
