### ISSUE TITLE
Could NOT find OpenMP_CUDA (missing: OpenMP_CUDA_FLAGS     OpenMP_CUDA_LIB_NAMES)

### ISSUE THREAD

**Issue by JosephBend** [LLNL/LEAP#124]
Hi,
I am trying to install LEAP without PyTorch.
I renamed the files and installed all the required packages:
    cmake 3.31.0-rc2, cuda 12.6 V12.6.77, VS 2022 (instructions ask for 2019) .

I get this error when trying to install LEAP1.23
  -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6 (found suitable version "12.6", minimum required is "11.7")
  -- Found OpenMP_C: -openmp (found version "2.0")
  -- Found OpenMP_CXX: -openmp (found version "2.0")
  CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
    **Could NOT find OpenMP_CUDA (missing: OpenMP_CUDA_FLAGS OpenMP_CUDA_LIB_NAMES)**

Do you have ideas how to solve this problem?
Thank you,

Joseph

**Comment by hws203** [comment]
You can set your own openmp_cuda path at your cmakelists.txt file. 

=============example===========
message(STATUS "set compipler")
set(OPENMP_LIBRARIES "/usr/local/Cellar/llvm/5.0.1/lib")
set(OPENMP_INCLUDES "/usr/local/Cellar/llvm/5.0.1/include")

set(OPENMP_LIBRARIES "/usr/local/opt/llvm/lib")
link_directories(${OPENMP_LIBRARIES})

**Comment by kylechampley** [comment]
Thanks for the suggestion @hws203 !!

Joseph, please try that and let us know if it resolves the issue.

**Comment by TiouTiouFang** [comment]
Hi,In windows system,how to set this ? Thank you!

**Comment by JosephBend** [comment]
Yes, Windows 10.

Thank you,

Joseph

**Comment by jsmaltz** [comment]
Which version of cmake are you using? I had this issue with cmake 3.31, but switching back to  3.18.4 resolved it.

**Comment by JosephBend** [comment]
3.31.0.rc2

3.18.4 is a very old release.
Also, the website states 3.23 or newer.
I will try 3.23.

Thank you!

Joseph

**Comment by JosephBend** [comment]
I was able to build Leap with cmake 3.23 .3.
I will try to test it later.

Admin: I recommend stating in the documentation to use cmake 3.23.3, which is the version that was tested. Newer versions may work too.

Thank you, jsmaltz!

**Comment by kylechampley** [comment]
Thanks everyone for their help.  Joseph, I updated the documentation to say 3.23.3.

Since you were able to compile, I am going to close this issue, but feel free to reopen it or another issue if something else comes up.
