### ISSUE TITLE
Apparently missing include of <algorithm> for windows compile

### ISSUE THREAD

**Issue by jsmaltz** [LLNL/LEAP#126]
Windows compile with VS2019 (and VS2017) fails because std::min and std::max are not defined. This is resolved by adding 
#include <algorithm> in the following files:

geometric_calibration.cu  
ray_weighting_cpu.cpp   
find_center_cpu.cpp    
sinogram_replacement.cpp    
cpu_utils.cpp        
file_io.cpp            
ramp_filter.cu         
cuda_utils.cu

**Comment by kylechampley** [comment]
That's very strange because it has always compiled fine for me on Windows.  Regardless, I added these includes which will be included in the next release.
