### ISSUE TITLE
Using FBP with modular beam that is close to a cone beam geometry

### ISSUE THREAD

**Issue by jsmaltz** [LLNL/LEAP#130]
I am trying to simulate a CT scanner where there are many tangential flat modules arranged in a curve. The geometry is very close to an ideal cone beam geometry. To do this, I repeat each source position num_modules times, so that numAngles = number of views * number of modules. This works fine with, for example, SART and RWLS, and the FORBILD example is reconstructed well, with the expected slight module boundary ring artifacts. But an FBP call with the same geometry produces something close to a constant value in the FOV, with no detail at all. There are no warnings or errors reported. Is this expected behavior? I guess rebinning as in d09_curved_polygon_detector_array.py is the preferred approach.

**Comment by hws203** [comment]
@jsmaltz It looks like my posting  #114 issue, please check your FBP call goes into modularBeamBackprojectorKernel_eSF() function rather than modularBeamBackprojectorKernel_SF(). If it is, then this is related to my posting issue(#114).

**Comment by kylechampley** [comment]
@hws203 please don't suggest that people use your suggestion from issue #114 .  If this worked for you, you got lucky.  One cannot replace the extended SF projectors for the regular ones.  This could lead to some big errors.

@jsmaltz, note that FBP reconstruction cannot be applied to any geometry.  Only some geometries defined as modular-beam will work.  LEAP should have printed an error message.  I'll see if I can work on this.

You are correct in that if you want to use FBP in your case, you should do what is outlined in d09_curved_polygon_detector_array.py.

**Comment by hws203** [comment]
@kylechampley I added to some more comments not to use  my temp solution to #114.

**Comment by kylechampley** [comment]
Has this issue been resolved?  If so, I'd like to close this issue.

**Comment by jsmaltz** [comment]
Yes, please close thanks.
