### ISSUE TITLE
Half-scan conebeam CT reconstruction (with offset) issue in Leaptorch

### ISSUE THREAD

**Issue by shaoyanpan** [LLNL/LEAP#131]
Hi:

We have an issue in leaptorch when we tried to reconstruct a half-scan CBCT in LEAPTorch. 

Firstly, we have an original CT in pytorch tensor (size of [1, 128, 512, 512]):
![image](https://github.com/user-attachments/assets/1bbd616e-e92e-4464-883e-10fea644e9eb)

Then, we project it:
# All the parameters are based on a conebeam imaging system, we can ignore them.
# (512.5+312) -> 312 is the offset
proj = Projector(forward_project=True, use_static=True, use_gpu=True, gpu_device=proj_device, batch_size=1)
proj.leapct.set_offsetScan(True) 
proj.set_volume(512, 512, 128, 1, 2, 0, 0, 0)
proj.set_conebeam(360, 768, 1024,  0.388, 0.388, 384.5, 512.5+312, proj.leapct.setAngleArray(360, 360.0),
                  1000, 1500, tau=0.0, helicalPitch=0.0)

sino = proj(img)

So we can have beautiful Xrays as:
![image](https://github.com/user-attachments/assets/e67ecc46-e073-4413-8a3d-681f42d53bc7)

Then, we reconstruct it:
rec_proj = Projector(forward_project=False, use_static=True, use_gpu=True, gpu_device=proj_device, batch_size=1)
rec_proj.leapct.set_offsetScan(True)
rec_proj.set_volume(512, 512, 128, 1, 2, 0, 0, 0)
rec_proj.set_conebeam(360, 768, 1024,  0.388, 0.388, 384.5, 512.5+312, proj.leapct.setAngleArray(360, 360.0),
                  1000, 1500, tau=0.0, helicalPitch=0.0)

recon = rec_proj(rec_proj.leapct.filterProjections(sino.clone()))
But the reconstrcuted image is like:
![image](https://github.com/user-attachments/assets/35a93bb2-ff50-4aaa-9eae-6c34e7ffcb6a)

Could you please help me to see is there any issue in the LEAPtorch? Do we need to do parker weighting by ourselves?

**Comment by kylechampley** [comment]
In the current version of LEAP, in order to do offset scan reconstructions your data must reside on the CPU.  The offset scan reconstruction may be done on the GPU, but the inputs must be on the CPU.  I'm sorry about this, LEAP should have printed an error message.

Anyway, this is something I am working on for the next release which should come out in the next couple of days.  I'll let you know when it is released.

Just out of curiosity, I thought you code looked a little weird.  Why not just do this:
```
recon = proj.leapct.fbp(sino)
```

**Comment by shaoyanpan** [comment]
Thank you so much! I am looking forward to see your new release! Let's see if I can run the offset reconstructionafter the release.

Btw, because I need to calculate the back-propagation gradient through the offset reconstruction. The leapct.fbp could not help me to do it, but rec_proj(rec_proj.leapct.filterProjections(sino.clone())) can do it. Really appreciate your work to allow back-propagation!
