### ISSUE TITLE
your paper's demo script request("Methods for Few-View CT Image Reconstruction")

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#133]
@kylechampley Could you add some demo script for checking your last paper's figure-6,7,8 with data?
Paper name is "Methods for Few-View CT Image Reconstruction".

**Comment by kylechampley** [comment]
Ya, that's a good idea, I'll try to dig those up.  I actually wrote that paper about three years ago and at that time was using LTT to make those results, so it'll take me some time to dig those up.
