### ISSUE TITLE
How do I control left and right side migration in offsetScan

### ISSUE THREAD

**Issue by Y7NINE** [LLNL/LEAP#135]
![image](https://github.com/user-attachments/assets/bf93ac16-e215-4aa3-ac3b-382cf30a55b8)
My shu data was biased on the left side but did not have a good result  
The raw data is generated in the tiger toolkit
![image](https://github.com/user-attachments/assets/fb09d42a-b05c-4274-b2d8-1ab6fd7b4f0f)

![image](https://github.com/user-attachments/assets/a75f1b30-a437-4fe4-aac6-15438a45c64a)

**Comment by Y7NINE** [comment]
![image](https://github.com/user-attachments/assets/e984b555-a6ab-4711-b0fe-4468121a41cd)
This is the image generated without offest
![image](https://github.com/user-attachments/assets/02418b99-5d6d-437e-b2f9-786c76a35d71)

**Comment by kylechampley** [comment]
I recently made a script that translates between TIGRE and LEAP parameters.  I am not advertising it because it is not done and does not handle all cases.  If you want to try it out, see here: [tigre_geometry_bridge.py](https://github.com/LLNL/LEAP/blob/main/utils/tigre_geometry_bridge.py).

**Comment by Y7NINE** [comment]
@kylechampley Thank you. I tried to reconstruct the example you gave, but the result was two symmetric overlaps. Have you ever encountered such a situation
![image](https://github.com/user-attachments/assets/c049e43e-975a-4df3-8df3-b66d51a194b4)
![image](https://github.com/user-attachments/assets/6a984f0a-0569-46a3-b0b9-1b80d095843e)
![image](https://github.com/user-attachments/assets/1de3744f-a7ce-4d61-8ab4-32973af4f25e)
![image](https://github.com/user-attachments/assets/e857b5a3-b839-4bf0-9181-45b1a53db663)

**Comment by Y7NINE** [comment]
The tiger kit can be rebuilt
![822fc121bc5f960e2d662f7d92ec8c2](https://github.com/user-attachments/assets/85e5f7cc-6ddb-47c9-be14-6e9fafd0b81a)

**Comment by kylechampley** [comment]
Try flipping the sign of the projection angles.

**Comment by Y7NINE** [comment]
@kylechampley Thank you very much for helping me again

**Comment by kylechampley** [comment]
Did that fix your problem?

**Comment by Y7NINE** [comment]
Yes
