### ISSUE TITLE
Is there a lagcorrection function in the leap package

### ISSUE THREAD

**Issue by Y7NINE** [LLNL/LEAP#136]

**Comment by Y7NINE** [comment]
Hello Is there a function like lagcorrection in the leap toolkit

**Comment by kylechampley** [comment]
Sorry, no, there is not.

**Comment by Y7NINE** [comment]
Ok, thank you.Recently, I have been focusing more on filtering techniques. I noticed that you mentioned BLF filtering and dictionary methods, and I have also experimented with Wiener filtering. After conducting some experiments, I compared the reconstruction results from Wiener filtering and BLF filtering, and found that the errors between them are very small. In this case, would it be acceptable to freely choose among these filtering methods depending on the situation

**Comment by kylechampley** [comment]
BLF should outperform Wiener filtering by a lot, especially if you want to preserve resolution and edges.

In my opinion, the best noise filters in LEAP are TV and Guided Filter.

**Comment by Y7NINE** [comment]
Oh my gosh! How is LEAP such an amazing package! Thank you so much for your guidance! I tried adjusting the TV iteration count and got great results!
![image](https://github.com/user-attachments/assets/950f6131-b3fd-421e-b9d3-1208ef4c55b2)
![image](https://github.com/user-attachments/assets/c88f03fd-c68c-4d25-8fa6-27a85283af73)
