### ISSUE TITLE
Is the FP and FBP part of the algorithm in LEAP based on ray-driven, pixel-driven, or distance-driven?

### ISSUE THREAD

**Issue by JoosenLi** [LLNL/LEAP#14]

**Comment by kylechampley** [comment]
I assume you meant "BP" instead of "FP" in your post, right?

The backprojection step of the FBP algorithms in LEAP uses a slight variation to the Separable Footprint (SF-RR) method.  All projectors in LEAP (expect non-axially aligned modular-beam data) use this method as well.
