### ISSUE TITLE
Problems : d31_scatter_correction.py

### ISSUE THREAD

**Issue by ProjX0** [LLNL/LEAP#140]
When running d31_scatter_correction.py, the message "Starting scatter simulation..." appears, but the process does not proceed further.
![Image](https://github.com/user-attachments/assets/73076a9e-aaa7-4eb6-88dc-95bf3169582a)

**Comment by kylechampley** [comment]
Give it time.  It is a very computationally expensive algorithm.

**Comment by ProjX0** [comment]
Oh, I thought it was a bug. It turns out i made a mistake. After waiting, I confirmed that it works. I thick we can close this issue. Thank you!
