### ISSUE TITLE
Modular geometry

### ISSUE THREAD

**Issue by ridoughi** [LLNL/LEAP#2]
Hello,
Is it possible to use the modular geometry configuration to compute projections pixel-by-pixel independently (Line projection) and combine batches of pixels from different viewing angles? I could not find enough documentation on how to use this option in the library. Could you please share some documentation or an example on this topic?

Thank you in advance.

Best regards,

**Comment by kylechampley** [comment]
Hi Ramzi,

LEAP is definitely lacking documentation and we are working on that.  I don't quite understand what you are asking?  Would you mind being a little more specific?  Thanks.

~Kyle

**Comment by kylechampley** [comment]
Documentation has been added explaining how modular-beam and CT volumes are specified.  There is a link to the documentation (a pdf file) on the wiki page.  Please look this over and let us know if this answers your question.
