### ISSUE TITLE
How to define an arbitrarily oriented geometry?

### ISSUE THREAD

**Issue by Ellen-D216** [LLNL/LEAP#21]

**Comment by kylechampley** [comment]
Hello.  This is done with our "modular-beam" geometry.  I think the best place to start is with some of our demo scripts.  See the following:
https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d04_modularbeam.py
https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d05_3DflashCT.py
https://github.com/LLNL/LEAP/blob/main/demo_leapctype/d21_walnut.py

Let me know if you have any further questions.

**Comment by Ellen-D216** [comment]
That is impressive! Thank you.
