### ISSUE TITLE
cbct post processing

### ISSUE THREAD

**Issue by hyaihjq** [LLNL/LEAP#22]
![9ebaea98c6e5d5d9b2f04d451cbcbe8a](https://github.com/LLNL/LEAP/assets/27874026/320da109-eba6-438f-bd79-9cc6db072b52)

What post-processing can be used to convert the right image into the left image？thanks

**Comment by kylechampley** [comment]
It's hard to say without knowing the source of the data and how the reconstruction was performed, but the artifacts I am seeing are most likely caused by scatter and/ or beam hardening.  LEAP does have beam hardening correction algorithms and these are applied to the data prior to reconstruction.  If you can provide me more information about this image I might be able to help out more.

**Comment by hyaihjq** [comment]
> It's hard to say without knowing the source of the data and how the reconstruction was performed, but the artifacts I am seeing are most likely caused by scatter and/ or beam hardening. LEAP does have beam hardening correction algorithms and these are applied to the data prior to reconstruction. If you can provide me more information about this image I might be able to help out more.

thanks for your reply. The right image is the result of reconstruction, and the left image is the visualization result after the software is opened. It can be determined that it is not related to reconstruction, but only the difference in post-processing.

**Comment by kylechampley** [comment]
Hmm, interesting. I guess you could try some denoising method. I’d check the visualization software manual.

**Comment by hyaihjq** [comment]
> Hmm, interesting. I guess you could try some denoising method. I’d check the visualization software manual.

thanks，Is there any way to enhance the contrast of the teeth area while reducing the contrast of the soft tissue?

**Comment by kylechampley** [comment]
Ya, TV denoising will do this.  Try this:
f_denoised = leapct.diffuse(f, delta, numIter)

where f is the reconstruction volume and numIter is the number of iterations (use 10-50 iterations).  You'll have to find the value of delta yourself.  The delta parameter specifies a transition value where
if the difference of two neighboring voxels are less than delta, then they will be blurred together, reducing contrast and noise
on the other hand if the difference of two neighboring voxels are larger than delta, then they will have little influence on each other and the edge between these will be preserved.

Thus you should set the delta parameter to be less than the difference between the teeth and the soft tissue.  I usually manually tune delta, but as a rule of thumb, I start with this guess:
delta = ((typical voxel value of material A) - (typical voxel value of material B)) / 20
where material A and B are materials that you want to have clear separation.

Good luck!

**Comment by hyaihjq** [comment]
> Ya, TV denoising will do this. Try this: f_denoised = leapct.diffuse(f, delta, numIter)
> 
> where f is the reconstruction volume and numIter is the number of iterations (use 10-50 iterations). You'll have to find the value of delta yourself. The delta parameter specifies a transition value where if the difference of two neighboring voxels are less than delta, then they will be blurred together, reducing contrast and noise on the other hand if the difference of two neighboring voxels are larger than delta, then they will have little influence on each other and the edge between these will be preserved.
> 
> Thus you should set the delta parameter to be less than the difference between the teeth and the soft tissue. I usually manually tune delta, but as a rule of thumb, I start with this guess: delta = ((typical voxel value of material A) - (typical voxel value of material B)) / 20 where material A and B are materials that you want to have clear separation.
> 
> Good luck!

thanks for your help! I will try your methed.

**Comment by kylechampley** [comment]
Any luck?  Do you still want to keep this issue open?

**Comment by hyaihjq** [comment]
> Any luck? Do you still want to keep this issue open?

no, thanks
