### ISSUE TITLE
Volume coordination

### ISSUE THREAD

**Issue by lc82111** [LLNL/LEAP#24]
![image](https://github.com/LLNL/LEAP/assets/6269232/0204a035-ecd1-4246-9419-e729db7ab7f4)

![image](https://github.com/LLNL/LEAP/assets/6269232/08156ad9-a068-462e-93f8-d543154aa276)
![image](https://github.com/LLNL/LEAP/assets/6269232/83111a5e-1e8c-4302-ba8f-83c234cf2f79)

I have a question regarding the orientation of the resulting volume. I believe the row direction of the volume corresponds to the left-right (LR) direction, and the column direction corresponds to the anterior-posterior (AP) direction. However, as shown in the image above, the row and column directions seem to be swapped in the resulting volume. Could you clarify the correct orientation of the rows and columns in the output?

**Comment by kylechampley** [comment]
Hello.

It's great to see a screen shot of my technical manual!  I wasn't sure people cared enough to read it.  I guess they do.

Anyway, yes, the axes in that figure are correct.  I also agree with your assessment of the rows and columns of that axial slice image you posted.  Did you expect that output to be rotated by 90 degrees?  The rotation of that image really depends on where you specify the start angle of your projections.  If you shift your projection angles by 90 degrees, your reconstructed image will also rotate 90 degrees.

I hope this helps!  If not let me know.

**Comment by lc82111** [comment]
Thank you for your response. Yes, I expected the output to be rotated by 90 degrees. And your explanation makes sense. I will try shifting the projection angles by 90 degrees and see if the output is rotated as expected. Great Work!
