### ISSUE TITLE
Questions about rebin function used in the curved detector

### ISSUE THREAD

**Issue by Starbucksmax** [LLNL/LEAP#27]
Thanks for your excellent work, it is the first work I've seen support curved detector for FDK reconstruction. So I tried it but the result seems not good. I'm wondering if I missed some part. The following is the code I'm used to reconstructed,
![image](https://github.com/LLNL/LEAP/assets/165836052/890069a0-305f-42fc-990d-974e83fbc1d6)

 If I didn't add the following lines, it worked but with some artifacts.
'leapct.set_curvedDetector()
fanAngles = np.array(range(numCols),dtype=np.float32)
fanAngles *= 180.0/np.pi
leapct.rebin_curved(g, fanAngles, order=6)
leapct.FBP(g,f)`
After added the rebin code, the final image will be blanked like the following:
![image](https://github.com/LLNL/LEAP/assets/165836052/d1f7c0a5-ecf1-4c79-8c0f-26d5953e1ceb)
Is there any way to solve this problem?
Thanks very much :)

**Comment by kylechampley** [comment]
It looks like you are following the d09_curved_polygon_detector_array.py demo script, but my best guess is that this is not what you want to do.  That script is for situations where your curved detector array is made of a collection of flat panel arrays.  But if you data is just one contiguous curved array, you should just follow the first demo script, d01_standard_geometries.py.

This is much, much easier and does not require rebidding.

Be sure to also add the line that tells LEAP to use a curved detector array:
leapct.set_curvedDetector()

You may also need to use the "numpy.ascontiguousarray" command because the dumpy transpose command does not always keep things contiguous.

My last command is that you value for pixelsizex seems way too large.  This should be the physical detector pixel size in mm.

Let me know if this resolves your problems or if you need any extra help.

**Comment by Starbucksmax** [comment]
Thanks for your reply. For you first suggestion, It did make much eaisier. 
For you second suggestion, you mean I should add one line like
`g = np.ascontiguousarray(g)`
after using
`g = np.transpose(g, (2, 1, 0))`?
About the pixelx issue this is my simulation data, cause the manual setting the pixelsizex is that large. 
The result is still not good, only the middle three slice is clear like the following upper, other still carry some artifacts like the following lower:
![good](https://github.com/LLNL/LEAP/assets/165836052/8213de1c-d9ba-4b7d-a830-b46e4aacf261)
![bad](https://github.com/LLNL/LEAP/assets/165836052/67b16fb7-0a2d-47a6-9650-dcfc3c9ca3c2)

**Comment by kylechampley** [comment]
I see.  Looks like it is mostly working, but some artifacts remain.

From your settings here, I would expect the reconstruction would have some issues because the detector row thickness is very large.  Are you sure you've got all the parameters specified correctly?  It is hard for me to judge without knowing the source of the data or having a copy of the data myself to test.

**Comment by Starbucksmax** [comment]
Yeah, I think the parameters should  specified correctly. Cause when I use my reconstructed code it works although slowly. 
I can send you the data, do you have time to check?

**Comment by kylechampley** [comment]
Sure, I could look at your data and try to find the issue, but I am traveling at this time and do not have access to a computer.  I will return home next Tuesday and could look into it then if you are willing to wait.

While you wait, you could try a few things.

Could you try flipping the rows of g like this:
g = np.ascontiguousarray(np.flip(g, axis=1), dtype=np.float32)

I'd also ask if you detector is not perfectly centered, you could look into changing the centerRow argument in set_conebeam.

One last question.  Is the really cone-beam data or is it a stack of fan-beams?

**Comment by Starbucksmax** [comment]
Yeah, I'm willing to wait.
I tried flipping the rows but didn't solve the problem.
I believe the detector is centered. And it is the really cone-beam data.
The following is the updated code.
![image](https://github.com/LLNL/LEAP/assets/165836052/71d23cdf-73f7-4268-aa6d-bf823424f3bc)
Have a good traveling time!

**Comment by Starbucksmax** [comment]
Hi, hope you have a great trip. Are you available to look into my data now? Where should I send you the link

**Comment by kylechampley** [comment]
Thanks.  Yes, I can look at it tonight.  Send the link to my email address which you can find here:
https://github.com/LLNL/LEAP/#authors

**Comment by kylechampley** [comment]
I was able to reproduce the results you posted above.  This data looks like it was simulated from the female XCAT phantom.  Is this correct?

First of all, the example reconstruction you have me had only 32 slices.  From my estimates, this volume can be reconstructed with the following volume specification:
leapct.set_volume(256, 256, 32, voxelWidth = 1.22, voxelHeight = 1.22)

In this case, the LEAP reconstruction definitely looked better than the one you provided.

I think everything in LEAP was specified correctly, so let me try to explain why some of the slices look strange.

1) You are getting significant artifacts from the fact that your detector pixels are nearly 12 times taller than they are wide.  I don't know of any CT system with such a geometry and I don't think anyone would design one like this.  If you want better results, you need to have detector pixels that are closer to being square.

2) Your cone angle is almost 12 degrees.  This is a large cone angle even for modern cardiac CT systems and you will definitely get so-called "cone-beam artifacts" from this large cone angle.  To mitigate these effects, you will need to use an iterative reconstruction algorithm or some other algorithm designed to mitigate such effects.

Let me know if you have any further questions.

**Comment by Starbucksmax** [comment]
Yes, it is the female XCAT phantom. Thanks for your time, I will create a more real detector to check it again.
Just one small question, using your volume specification why the slice between 12-15 will remain nearly the same?

**Comment by kylechampley** [comment]
Your detector row spacing is 410/32 = 12.8125 mm, but the effective spacing at isocenter (center of rotation of the scanner) is 12.8125 * sod/sdd = 7.2829 mm.  Thus the effective slice thickness of the reconstruction volume is about 7.2829 mm.  That means that the reconstruction will be mostly constant within 7.2829 mm thick sections.  If you chose reconstructed slices where the voxel height was 1.2 mm, then sections of 6 slices will be approximately constant (7.2829/1.2 = 6.0691).

**Comment by Starbucksmax** [comment]
Thanks!
