### ISSUE TITLE
Can't use libleapct.dll wheninstalled manually on Windows

### ISSUE THREAD

**Issue by LabTelc** [LLNL/LEAP#32]
When installed manually with CUDA Toolkit 12.4, there is a dependency missing.

```
FileNotFoundError: Could not find module 'C:\Users\user\.conda\envs\LEAP\Lib\site-packages\libleapct.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

The library libleapct.dll needs `cufft64_10.dll`, but CUDA Toolkit's file is named `cufft64_11.dll`. 
The issues can be resolved by copying cufft64_11.dll in cuda toolkit installation folder and renaming the copy to cufft64_10.dll.

**Comment by kylechampley** [comment]
Please read my post to your other issue; hope it works.  Looks like you went through quite a bit a trouble getting this to work, but glad you found a workaround.
