### ISSUE TITLE
LEAP installation Issue

### ISSUE THREAD

**Issue by cloner99** [LLNL/LEAP#36]
Hi!

I am working for building a docker file and a docker image for LEAP. 

But things got wrong on installation on LEAP on the current version.

Despite I'm using Leap very well on my local computer, and I'm testing for several environments on several server, the installation of LEAP occurs the same error on every attempts.

When executing pip install . , the error below outcame.

root@workspace-2hw8cpn8igqf-0:~/LEAP# pip install .
Processing /root/LEAP
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-bok50650

Earlier versions of Leap (like versions from Feb 2024 or late 2023) didn't shown this kind of error, so something might gone wrong when fixing other problem from then. 

I hope this problem will go well.

**Comment by kylechampley** [comment]
Hello, would you please re-run the LEAP pip install with the -v flag and send me the screen output?  Thanks.

**Comment by cloner99** [comment]
> Hello, would you please re-run the LEAP pip install with the -v flag and send me the screen output? Thanks.

here is the screenshot.

![image](https://github.com/LLNL/LEAP/assets/12511034/7b8fb1ca-f549-4e18-a2e1-abde44482cb6)

**Comment by kylechampley** [comment]
It looks like you need to install a newer version of cmake.  LEAP requires that you use version 3.23 or higher.
