### ISSUE TITLE
long height sample case with leap's function

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#42]
@kylechampley.  At the case of long length sample as like cylinder battery, there is some tile issue of pivot which is the point of rotation axis at the sample.  In other words, the true CoR of the center of detector is different from the bottom one. Such case, I can not overcome this issue with your new detector rotation function. Could you give me any alternative solution at this case?  
As you can see below, the center slice is good but the bottom slice has wrong points at the boundary of circle.

1. center slice:
![slice_385](https://github.com/LLNL/LEAP/assets/73321363/45ad163a-02a2-4e32-8c1c-7476c0f25bec)

2. bottom slice:
![slice_999](https://github.com/LLNL/LEAP/assets/73321363/1647f9fa-09ab-40dd-955a-9519dfc04ceb)

**Comment by hws203** [comment]
I tilted my all projection images by the angle which extracted from the CoR between center and bottom ROI(3008x10).
Then I can see both correct slices in all range of detector. But It is too slow and clumsy solution. I wonder whether there is any better one.  

![slice_385](https://github.com/LLNL/LEAP/assets/73321363/5eede884-b80a-4aee-8aed-950ec183e60e)

![slice_999](https://github.com/LLNL/LEAP/assets/73321363/91345cb8-9c2f-4d80-b5d0-b66cb33e48f9)

**Comment by kylechampley** [comment]
Yes, that is a common method to estimate tilt angles.  I'll comment more about this in another post.

**Comment by kylechampley** [comment]
I'm going to close this issue because it seems like things have been resolved.  If you find another bug, please open a new issue, but if you just want to start a conversation about a topic, please open a new discussion thread instead.
