### ISSUE TITLE
Calculate the HU value

### ISSUE THREAD

**Issue by stefenmax** [LLNL/LEAP#48]
The Hounsfield scale of CT is set around water measuring 0 HU. By altering the attenuation level (mid-HU value) and range (extent of gray scale) at which the image is viewed, the tissue to be displayed can be determined.
Will LEAP add a function to calculate the HU value automatically?

**Comment by kylechampley** [comment]
Yep, that's one of the reasons why I developed the [XrayPhysics](https://github.com/kylechampley/XrayPhysics) package.  Just install this package and then run the following code: 

```
from xrayphysics import *
physics = xrayPhysics()
physics.use_mm()
f = 1000.0/physics.mu('water', effectiveEnergy)*f - 1000.0
```

For this to work you'll need to know the effective x-ray energy (in units of keV) of the data; see the effectiveEnergy variable in the code above.  This'll be a number between 50 and 100 keV for most medical purposes.

**Comment by stefenmax** [comment]
I used the 3D reconstructed result from LEAP and set the effective x-ray energy to 100. But the HU value calculated is strange from -4981677.0 to 132672040.0. Is it normal?
from xrayphysics import *
physics = xrayPhysics()
physics.use_mm()
effectiveEnergy = 100
f = np.load('../recon_npy/recon1.npy')
f = 1000.0/physics.mu('water', effectiveEnergy)*f - 1000.0
print(np.min(f[f.shape[0]//2,:,:]))
print(np.max(f[f.shape[0]//2,:,:]))

**Comment by kylechampley** [comment]
Ya, those values are not normal.  But based on those values, it seems like before that scaling, i.e., the values in your npy file, were in the range: -85 to 2264.  That range of values looks like Modified Hounsfield Units (MHU) which is HU+1000.0.  Thus, I think that data that went into the LEAP reconstruction was already scaled.  I think all you need to make that result in HU is to subtract 1000.

**Comment by stefenmax** [comment]
aha, that make sense. Thanks!
