### ISSUE TITLE
Cylinder type Sample Auto-calibration Issue

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#49]
I have checked your new v1.13 auto-cal function with my 4680 battery projection. And I can see that there is some issue at that case.

1. Center slice:
 
![autocal_4680_center_slice](https://github.com/LLNL/LEAP/assets/73321363/1ea6d697-31ff-426c-8e6b-0b5ca4a59ad7)

2. Bottom slice:

![autocal_4680_bottom_slice](https://github.com/LLNL/LEAP/assets/73321363/926dcaad-e75e-42bd-bfe1-0940a2867675)

3. console log:

![autocal_4680_console_log](https://github.com/LLNL/LEAP/assets/73321363/1f5e8079-6d54-4d95-8e93-4f7bdaea3ce1)

I will send my full test script code and my sample image location by your e-mail. I guess that the issue is related to modular-beam converting action because the if np.abs(res.x[2]) > 0.1: condition matched and go into below sub-routine, then this issue happens.

Best regards.

**Comment by kylechampley** [comment]
There is a typo in the demo script.  Line 214 should be: leapct.convert_to_modularbeam()

Anyway, this is just an estimation algorithm and the authors of the paper from which I got the algorithm say that the cost function is only locally convex, so if your initial guess is not close to the true solution, one may only converge to a local minimum.

Also for this code to work the projections must not be truncated.  It also helps to correct for flux modulation.  A flux modulation correction method can be found in the makeAttenuationRadiographs function in [leap_preprocessing_algorithms.py](https://github.com/LLNL/LEAP/blob/main/src/leap_preprocessing_algorithms.py)
See the "ROI" argument in this function.

**Comment by hws203** [comment]
I found the bug point at your d12_geometric_calibration.py at the case of tilt angle bigger than 0.1.

Please check below picture.

![D12_Geocal_bug](https://github.com/LLNL/LEAP/assets/73321363/5e4ecfa7-1f52-4bb1-8e8b-987d985de8d8)

![D12_Geocal_bug2](https://github.com/LLNL/LEAP/assets/73321363/a1ac293a-ab74-449d-afa3-c58e21acdfb8)

**Comment by hws203** [comment]
I commented out the first step of  the estimation algorithm(costFcn_rc).  And run only the second costFcn_rct minimize for tilt angle. The first step minimizing is not effective currently owing the res.x[0] and res.x[1] issue.

**Comment by hws203** [comment]
@kylechampley  How about using the value from your leap.find_centerCol() 's result for the initial guess param for optimizing of your consistency-cost function. then you may focus on the narrow valley area for finding the min-values of res.x[0~2].

**Comment by kylechampley** [comment]
That sample script is a demonstration of a capability in LEAP, rather than a prescription of how to perform geometric calibration on an arbitrary dataset.  All CT systems are unique and may require different methods.  Thus, the best I can do is provide users with tools to use, but they will have to find the right way to use those tools to get the best results.

**Comment by hws203** [comment]
ok, test script usage method is user's side role, but I wonder there is no needs to check the res.x[0] or res.x[1] ?

**Comment by hws203** [comment]
I can see that your current GPU code of consistency_cost() is just for finding the tilt angle.  So it should not be used for center.

**Comment by kylechampley** [comment]
Those are the estimates provided by the optimization algorithm.  They might not be correct, but they are values that reduce the cost function.  I suggest that these be verified by reconstruction.  Single slice reconstructions are often sufficient for this verification.  You can also use the parameter_sweep function which I personally find very useful.

Regardless, the "proper" way to do CT is to scan some calibration phantom, like the so-called "ball phantom".  These scans usually provide good results.

**Comment by hws203** [comment]
Thanks for your recommendation. I will try it Today.^_^

**Comment by hws203** [comment]
Yes, parameter_sweep is useful, and I found that my cylinder type sample has a special position which is lower positioned from center line of row in detector.  So as you can see below if I use the centerRow+100 position, then your inconsistency recon shows very clear tilt angle which is best. But at the center of row. it shows broad area of cost values which may bring some incorrect res.x[0] or res.x[1].

![sweep_center_row](https://github.com/LLNL/LEAP/assets/73321363/b3480bac-6a01-485b-a023-7719d0d9ee44)

![sweep_center_plus100_row](https://github.com/LLNL/LEAP/assets/73321363/7198ff8e-8331-470d-804d-970e2e807175)

**Comment by hws203** [comment]
@kylechampley I did check the deltaCol and deltaRow with my new centerRow position(+100). And I could see that this new row position can not cover the weakness of res.x[0] or res.x[1].  Anyway your new consistency-cost shows the robust finding of tilt angle of my cylinder sample. So I will use your new consistency-func for tilt and find_centerCol for centerCol.

If you there will be no more updating about this issue, please close this issue.

**Comment by hws203** [comment]
I did more same test with another row position rather than centerRow+100, then it shows also weak result in even res.x[2]. So I do better use parameter-sweep.
