### ISSUE TITLE
powell method optimizer function implementation by gpu code 

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#52]
@kylechampley  Do you have any plan to implement current python's scipy.optimize.minimize into your own gpu c++ code ?
That could bring faster auto geo-calibration result.

**Comment by kylechampley** [comment]
No, I had no intension to do such a thing.  The main computations in performing this geometric calibration are with the calculation of the cost function itself which I already implemented for the GPU.

**Comment by hws203** [comment]
I see you can close this issue.
