### ISSUE TITLE
bad pixel correction feature

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#57]
@kylechampley  Is there any bad pixel correction feature at Leap?  I can see that if the detector has some dark or white bad pixel then I can see below result slice at a specific slice. I adapted a blur filter when it reads  projection images, but that can not cover this issue(dark circle).

![bad_pixel](https://github.com/LLNL/LEAP/assets/73321363/aacfbe79-4111-4635-b256-c6fe8ac75c0b)

**Comment by kylechampley** [comment]
Yes, there is. See the “outlierCorrection” algorithm. There is a demo script for this, see d14_outlierCorrection.py

**Comment by hws203** [comment]
I checked both your outlierCorrection(A) and outlierCorrection_highEnergy(B). And I can see that the first one does not fully cover this issue, there is still dark circle. But the second one(B) can cover fully this issue, so I can not see any dark circle. 
The second method needs more time to do for three times filer_2d.

**Comment by kylechampley** [comment]
You should be able to get better results from the standard outlier correction algorithm. Try using a bigger window size

**Comment by hws203** [comment]
Yes it is. Windows size is critical factor. The size bigger than 5 of  the standard outlier correction works well for my case. Thanks.

**Comment by hws203** [comment]
I will close this issue.
