### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by tivnanmatt** [LLNL/LEAP#6]
When I try to install with "pip install ." it fails to build the wheel returning the following error. There seem to be several cases named parallelBeam rather than parallelbeam.

src/main_projector.cpp:606:15: error: ‘class tomographicModels’ as no member named ‘set_parallelBeam’; did you mean ‘set_parallelbeam’?
        606 |     tempModel.set_parallelBeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, centerRow, centerCol, phis);
            |               ^~~~~~~~~~~~~~~~
            |               set_parallelbeam
      error: command '/usr/bin/gcc' failed with exit code 1

**Comment by kylechampley** [comment]
Really sorry about this.  If you look at the recent activity on this repo, there have been many, many changes.  Throughout these changes, we have fixed many things, but sometimes broke other things.  I just merged new code into main that should compile and run fine now.

We are nearly done with most of our major changes.  We are going to run some more verification tests and then release version 1.0 by the end of the year.

**Comment by tivnanmatt** [comment]
No problem, I understand. I have been using version 0.9 since october.
Smoothly works with PyTorch and cuda. I’m an instructor/researcher of
radiology at Massachusetts general hospital. Let me know if you need any
community support with the code. I have some scripts using LEAP projectors
for penalized likelihood model based iterative reconstruction with an
approximate newtons method algorithm.

Best,
Matt Tivnan

**Comment by kylechampley** [comment]
Hi Matt,

I think open-source projects really thrive when they have community support, so sure!  What did you have in mind?  Might be best to continue this conversation over email.  My email address is my last name at gmail.com.

Also note that there have been HUGE changes since version 0.9, including many iterative reconstruction algorithms.

~Kyle
