### ISSUE TITLE
The NaN problem in Iteration Reconstruction

### ISSUE THREAD

**Issue by PirateRicher** [LLNL/LEAP#64]
Hi

When I used the IR like SART in LEAP, I tried to use the noise which from the diffusion model, as the initial input and the SART work. But when I printed the output, I found there are many NaN (Not all,but most ) in the results.That was very strange.

I would like to know are there any limitations on the IR input? And why would the results will work out NaN results?

Best,

**Comment by PirateRicher** [comment]
And here is the output, where x_next_2 is the input of IR:
x_next_2:tensor([[[[ -95.6140,  116.9636,  131.4474,  ..., -109.2653, -243.9316,
            149.8053],
          [-389.6929,  -13.0061,  401.6941,  ..., -143.1181, -112.7916,
           -189.2075],
          [ 123.8581,  235.6588, -209.9771,  ...,  260.4404, -272.1484,
            -56.4938],
          ...,
          [ -62.2912,  105.1640,   54.2454,  ..., -116.4751,   16.5664,
            292.3446],
          [ -39.8778,  150.4883,  193.5163,  ...,  -50.5344, -190.6261,
            416.4268],
          [-711.3794,   -9.8581,  156.0905,  ..., -438.4397, -486.9677,
            101.1560]]]], device='cuda:0', dtype=torch.float64)
x_next2_shape:torch.Size([1, 1, 512, 512])
x_next2 max:1210.9393616716463
x_next2 min:-1165.4740936310213
proj_shape:torch.Size([1000, 1, 900])
SART iteration 1 of 10
SART iteration 2 of 10
SART iteration 3 of 10
SART iteration 4 of 10
SART iteration 5 of 10
SART iteration 6 of 10
SART iteration 7 of 10
SART iteration 8 of 10
SART iteration 9 of 10
SART iteration 10 of 10
x_nextIR:tensor([[[  0.0000,      nan,      nan,  ...,      nan,      nan, 149.8053],
         [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
         [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
         ...,
         [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
         [     nan,      nan,      nan,  ...,      nan,      nan,      nan],
         [     nan,      nan,      nan,  ...,      nan,      nan,      nan]]],
       device='cuda:0', dtype=torch.float64)
x_nextIR_shape:torch.Size([1, 512, 512])
x_nextIR max:nan
x_nextIR min:nan

**Comment by kylechampley** [comment]
It seems like your inputs are doubles, but LEAP requires 32-bit floats.  What version of LEAP are you using?  The newest version, v1.15, should check your data type and return an error if they are invalid (i.e., not float32, wrong shape, etc).

I'm not sure what kind of input your are giving SART, but tomographic iterative reconstruction algorithms do not perform well when they are seeded with input that have high frequency components.  Some of these high frequency error will never go away and others will take an enormous amount of iterations to suppress.

**Comment by kylechampley** [comment]
Are you still having issues once you switched to using 32-bit floats?

**Comment by PirateRicher** [comment]
I'm so sorry for not replying to your message earlier, I have tried to change the data to 32-bit float, and the problems are solved. Thanks for your help!
