### ISSUE TITLE
curved detector

### ISSUE THREAD

**Issue by stephoog** [LLNL/LEAP#7]
Hey!  Does LEAP handle curved detectors?  I am working with medical data and they all have curved detectors so I need software for this.

**Comment by kylechampley** [comment]
Hello,

I'm actually working on that feature now.  It should be ready by the end of the month.  I'll let you know when it's done.

~Kyle

**Comment by kylechampley** [comment]
Although it is not yet officially released, LEAP can now process cone-beam curved detector data.  To specify a curved detector run the following command after the call to set_conebeam(...)

leapct.set_curvedDetector()

**Comment by stephoog** [comment]
It works!! Thanks!
