### ISSUE TITLE
Remove the limitation of 5 degree aligned to z-axis

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#72]
@kylechampley, I did check your d32_laminography.py at your latest v1.16. version And I can see good and fast result  even I use the leapct.FBP() function for the reconstruction at the 5 degree tilt of detector's row without iterative method.  So I tried to remove some returning code at leapct to see the result from more over 5 degree of FBP(). But there is some error in ramp filter processing of leapct. 
Could you help me how to remove this 5 degree limitation for my test?  Because the recon time is very critical for my case.

**Comment by kylechampley** [comment]
Hello.  I don't want to remove that restriction for everyone, but if you want to remove it yourself, it is actually pretty easy.  Just change line 1071 of src/parameters.cpp.

OK with you?  Let me know how it goes.

**Comment by hws203** [comment]
Oh  it is easy,  now I can see my test result at over 5 degree. Thanks for your comments.

**Comment by kylechampley** [comment]
Great!  How does the reconstruction look?

**Comment by hws203** [comment]
Your doFBP also shows a good result after laminography reconstruction with 50 degree angle as like below.
If the geometry params are correct, then fbp also makes a good slice too.
<img width="773" alt="oct_coil" src="https://github.com/LLNL/LEAP/assets/73321363/06d18f4a-2691-4085-a859-13203b163672">

**Comment by hws203** [comment]
Below is your demo laminography result with fbp and 40 degree angle.

<img width="1115" alt="lamino_50_degree" src="https://github.com/LLNL/LEAP/assets/73321363/8477a09a-d36c-4369-8b7c-5de0c87e9b05">
