### ISSUE TITLE
Issue with Helical Reconstruction Geometry Parameters in Leap

### ISSUE THREAD

**Issue by baharehhj** [LLNL/LEAP#73]
Hello,

I'm working on helical reconstruction using the Leap library and trying to match the reconstruction geometry parameters to those provided in OpenRecon. Here is my code:

`import sys
import os
import time
import numpy as np
import torch
from leapctype import *
leapct = tomographicModels()

numCols = 350
numTurns = 3
numAngles = 1080
pixelSizex = 2
pixelSizez = 2
numRows = 20

leapct.set_conebeam(numAngles, numRows, numCols, pixelSizex, pixelSizez, 0.5 * (numRows - 1), 0.5 * (numCols - 1), leapct.setAngleArray(numAngles, 360.0 * numTurns), 100, 150, helicalPitch=1.0)
leapct.set_normalizedHelicalPitch(1.0)
leapct.set_volume(128, 128, 128)
leapct.print_parameters()

f = leapct.allocateVolume()
f = torch.tensor(f, dtype=torch.float32).to('cuda')

g = np.load('./helical data/proj_spiral_rotated.npy')
g = torch.tensor(g, dtype=torch.float32).to('cuda')

startTime = time.time()
leapct.FBP_gpu(g, f)
print('Reconstruction Elapsed Time: ' + str(time.time() - startTime))
leapct.display(f)
`
I used the geometry from OpenRecon and set the values from this [script](https://github.com/hengyongyu/OpenRecon/blob/master/Helical_Rec_Curve.m).

However, my reconstruction results do not match my expectations. Here is what I get:
![Screenshot_4](https://github.com/LLNL/LEAP/assets/42694381/0a3970f9-a577-486d-ad9b-257100a7f110)
But I am expecting this:
![Screenshot_5](https://github.com/LLNL/LEAP/assets/42694381/4cd63e27-20ef-4c54-a1a5-580a977b4b61)

Could you please guide me on what I might be doing wrong? Any insights or suggestions would be greatly appreciated. Thank you!

Best regards,

**Comment by kylechampley** [comment]
Did this resolve your issue?

**Comment by baharehhj** [comment]
> Did this resolve your issue?

Thank you for your help, but unfortunately it didn't work

**Comment by kylechampley** [comment]
If you are interested, you can send me your data and I can have a look.

**Comment by baharehhj** [comment]
> If you are interested, you can send me your data and I can have a look.

Thanks for offering to help! Here's the link to my data: [https://drive.google.com/file/d/1lUph_spDSMObcCLJJ5aQHsWNWB78Brcu/view?usp=sharing](url)
[https://drive.google.com/file/d/1scmv7IUQFqNQh4_vIfSdKljC_a4skOke/view?usp=sharing](url)

**Comment by kylechampley** [comment]
Thanks for posting those links.  I found a few issues.

First of all, the data dimension did not match what LEAP expects.  You have to swap axes 0 and 1 and then swap axes 1 and 2.

Second, it appears that your data is in so-called cone-parallel coordinates.  This is a coordinate system where you take cone-beam data and rebin each of the fan-beam to parallel-beam data.  LEAP does not yet support cone-parallel coordinates.  This is something I am working on now, but it won't be ready until a couple of weeks.

Thus, you could wait a couple of weeks until this is ready or if it is possible, get the data before it was rebinned to cone-parallel coordinates.  In that link you posted about the source of the sample script, I see that this rebinning is happening on line 56.

**Comment by kylechampley** [comment]
Here you go, this should work.  I'm not completely sure I got the helical pitch parameter correct, but the reconstruction looks good.  Oh, and I think I was wrong about the data.  I think this is cone-beam data and the rebinning hadn't happened yet.

```
import sys
import os
import time
import numpy as np
import torch
from leapctype import *
leapct = tomographicModels()

dataPath = os.path.dirname(os.path.realpath(__file__))

sod = 100.0
odd = 50.0
sdd = sod+odd
numCols = 350
numRows = 20
numTurns = 3
numAngles = 1081
angularStep = 1.0
pixelWidth = np.tan(0.232*0.5)*sdd*2.0/float(numCols)
pixelHeight = 2.0/float(numRows)

leapct.set_conebeam(numAngles, numRows, numCols, pixelHeight, pixelWidth, 0.5*(numRows - 1), 0.5*(numCols - 1), leapct.setAngleArray(numAngles, angularStep * numAngles), sod, sdd)
leapct.set_curvedDetector()
leapct.set_normalizedHelicalPitch(1.0*1.5)
#leapct.set_helicalPitch(0.2894)
leapct.set_default_volume()
leapct.print_parameters()

f = leapct.allocateVolume()
f = torch.tensor(f, dtype=torch.float32).to('cuda')

g = np.load(os.path.join(dataPath, 'proj_spiral_reshape.npy'))
g = np.ascontiguousarray(np.swapaxes(g,0,1), dtype=np.float32)
g = np.ascontiguousarray(np.swapaxes(g,1,2), dtype=np.float32)
g = torch.tensor(g, dtype=torch.float32).to('cuda')

leapct.FBP(g, f)
leapct.display(f)

```

**Comment by baharehhj** [comment]
Hi @kylechampley,

Thank you so much for your help and the detailed script. I really appreciate the effort you put into resolving my issue.
I've implemented the changes you suggested and the reconstruction looks good now.
I'll keep an eye on the upcoming updates for LEAP, but for now, this solution works perfectly for my needs.

Thanks again for your support!

**Comment by kylechampley** [comment]
Happy to help. Don’t forget to double check the helical pitch setting.
