### ISSUE TITLE
laminography zero recon slice issue

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#74]
@kylechampley  During my test of  oblique ct image, I can see all zero slice which made by leact's FBP.
Python console says that all process have been done well, but the recon slice have no information.

I sent the projection image link and script file too by your e-mail.  Please check this issue.

<img width="1586" alt="all_slice_zero" src="https://github.com/LLNL/LEAP/assets/73321363/98864d91-cd45-4adf-943c-abb21bddd63e">

<img width="957" alt="tilt_detector_X" src="https://github.com/LLNL/LEAP/assets/73321363/ef1e6c0d-73c7-418f-a35f-4d4080159c54">

**Comment by kylechampley** [comment]
I did not receive an email from you.  Are your rowVec and colVec vectors always perpendicular?  They need to be.

**Comment by jeffhwang02** [comment]
I sent it by your gmail address.  Yes maybe the colVecs and rowVecs are not orthogonal. Maybe I should change the order of two vectors modification. at my test script.

**Comment by hws203** [comment]
Yes. It is orthogonal issue, after place the modification of colVecs at first and then the rowVecs,  then recon is now normal.  
Thanks for your insight comments.
