### ISSUE TITLE
Out boundary brightness issue

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#78]
@kylechampley , As you can see below, even I used the leapct.set_diameterFOV(), I can see some bright boundary area which makes the valid inner area too dark.  Is there any method to solve this issue without using the set_diameterFOV() ?

<img width="324" alt="outboundary_brigtness" src="https://github.com/user-attachments/assets/0a2d657d-3d70-4722-8f39-18af5505ce91">

**Comment by kylechampley** [comment]
Try using this command
leapct.set_truncatedScan(True)

**Comment by hws203** [comment]
Thanks so much. That command solves this issue.
<img width="281" alt="outboundary_brigtness_clear" src="https://github.com/user-attachments/assets/ada44942-ee74-4e92-8a63-5b50cef611e8">
