### ISSUE TITLE
meet some problem when install LEAP

### ISSUE THREAD

**Issue by JoosenLi** [LLNL/LEAP#8]
Hello developer, I want to install the LEAP function library on my X86-linux server. After downloading and changing the current folder with cd, I executed pip install . and encountered an error: ERROR: Could not build wheels for leapct, which is required to install pyproject.toml-based projects. Can you provide a solution?
<img width="559" alt="fbf505127cbb445ab56424d8761b5d3" src="https://github.com/LLNL/LEAP/assets/75923334/28f0b3d8-21ff-4fc5-a9aa-845cdde7e68d">

**Comment by JoosenLi** [comment]
Additional information about my environment is as follows: CUDA version is 11.3, PyTorch version is 1.13.1, GCC version is 10.5.0 (Ubuntu 10.5.0-1ubuntu1~22.04), and the graphics card is NVIDIA GeForce RTX 3090.

**Comment by kylechampley** [comment]
Thanks, this is helpful.  LEAP requires CUDA 11.7.  I updated the dependencies on the wiki page here:
https://github.com/LLNL/LEAP/wiki/Installing-and-Using-LEAP
