### ISSUE TITLE
Projection image's intensity slope reverse issue

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#81]
@kylechampley   About the intensity shift issue, I also saw it in lami-case too, as you can see at below image, the intensity of bottom is brighter than the one of top which is reverse in real projection image. Did you adapt this feature artificially ? If not, it should be reverse.  Below is issue regeneration script and image. the phantom is same with your original demo script.

<img width="995" alt="issue_genh_script1" src="https://github.com/user-attachments/assets/62b30098-eddf-4392-a1de-d9ba65cfe527">
<img width="936" alt="issue_genh_script2" src="https://github.com/user-attachments/assets/cfa562b1-f816-434d-88e4-359cf67d191f">

![name_0001](https://github.com/user-attachments/assets/815dcfb8-e732-47de-a8c9-786feafadd52)

**Comment by kylechampley** [comment]
It makes sense to me.  I'll explain my thinking.

The top of your image is truncated, so it is clear that this is the side of the object closest to your x-ray source.  The bottom of your image is furthest from your x-ray source.  The rays are passing through your object more obliquely for the part of the object that is further from your x-ray source (again bottom of your image) and thus the length of intersection through is object is longer, leading to more attenuation (brighter image).

**Comment by hws203** [comment]
As X-ray source is longer from the detector, the image intensity is also much darker, and the attenuation is stronger, it is also showing darker image.  why you think it reverse ?  Do you mean the negative log transform one?

**Comment by kylechampley** [comment]
The image you posted is just a line integral transform (attenuation data) through the object and thus x-ray intensity is not modeled.  This is not the same as what one would see from the raw detector counts of real data.

**Comment by hws203** [comment]
I see, then same intensity slope from top to bottom may be better I think.

**Comment by kylechampley** [comment]
Sorry, I don't understand your comment.

**Comment by hws203** [comment]
If  x-ray intensity is not modeled, then the projection image should be just line integral transform intensity without any weight factor between top and bottom.

**Comment by kylechampley** [comment]
That's correct that the x-ray intensity is the same across the beam, but like I explained above the rays at the top of your image have a shorter path length through the object then the rays at the bottom of your object because of the angle at which they pass through the object.  The intensity of the image is correct.

**Comment by hws203** [comment]
@kylechampley  As you can see below image, other package of x-ray physics projector simulator shows same intensity between top and bottom.

<img width="763" alt="tilt_project" src="https://github.com/user-attachments/assets/6f915602-7f3e-4005-9117-172c20792323">

**Comment by kylechampley** [comment]
That’s a different object and a different scan geometry. If LEAP used that object and geometry, the intensity would also be the same top and bottom.

**Comment by hws203** [comment]
I change parallel beam to cone beam.
<img width="566" alt="tilt_project2" src="https://github.com/user-attachments/assets/50e85645-9afa-4952-9cd9-60e9e0b99b2d">

**Comment by kylechampley** [comment]
Nope, still not the same object, so the comparison is invalid.

**Comment by hws203** [comment]
You are right, there is no problem at your leap package. Your projection image  just looks like an inverted one from real raw image from detector.
I checked it by changing your leap's lami-phantom to cube box and check the projection image as like below.

<img width="445" alt="rectnage3" src="https://github.com/user-attachments/assets/cc916259-4768-453d-9f4e-3bc8a6f881db">
<img width="464" alt="rectnage4" src="https://github.com/user-attachments/assets/e8a8d9b9-2fc3-41fa-9814-87ed6137ea36">
