### ISSUE TITLE
Phantom jig  calibration supporting

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#83]
@kylechampley  As you may know most ct-reconstruction package support their own phantom jig calibration feature.
Is there any plan for this feature in leap package or already has ?

**Comment by kylechampley** [comment]
What is a “phantom zig”? Could you send a link that describes this?

**Comment by hws203** [comment]
I sent a related data to your gmail, please check it.

**Comment by kylechampley** [comment]
The word "zig" does not appear in this document.  Could you point me to the correct page?

**Comment by hws203** [comment]
phantom-based alignment, refer to 102 page.  I called the phantom which made for this feature as like "phantom-zig".

**Comment by kylechampley** [comment]
OK, I see.  This just entails scanning a calibration phantom and automatically determining the CT geometry parameters.  I've never heard of the term "zig" before.  At LLNL we used a so-called "ball phantom" which was a stack of metal balls.  NSI also uses this kind of calibration phantom as well.

Ya, I could add this to a future release.  Currently I am finishing up support for cone-parallel coordinates.  After that I need to work on the GUI and routines to process data that is too big for CPU RAM.  Ball phantom calibration could be implemented after these features.

**Comment by hws203** [comment]
I see, Thanks for your detailed explanation. If that feature added, I will check it later.

**Comment by kylechampley** [comment]
Ball phantom calibration function has been released in [v1.22](https://github.com/LLNL/LEAP/releases/tag/v1.22).
