### ISSUE TITLE
display unblock

### ISSUE THREAD

**Issue by karimi-2024** [LLNL/LEAP#85]
Hello, 
Can the napari viewer used by leapct.display be unblocked so that a script can continue or the command prompt becomes available?
Also, can a title bar for user-text be displayed on the napari viewer? 
Thank you!

**Comment by kylechampley** [comment]
Hello.  Unfortunately, I do not know how to unblock napari.  If you look at the display function it is basically doing this:
```
import napari
viewer = napari.view_image(x, rgb=False)
napari.run()
```

It is the last command, napari.run() that is blocking, but if you remove this line, then napari window will open and then immediately close.  I don't know how to keep it open.  I searched around a bit, but did not find a solution, but I'm sure someone has found a way to do this.

**Comment by hws203** [comment]
You can use napari console command by using the windows tap on the top menu of napari.

<img width="1365" alt="napari" src="https://github.com/user-attachments/assets/d1b01c5d-25d7-4ef3-8e08-f8791a6cbb1b">
