### ISSUE TITLE
sinogram order base back-projection supporting

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#89]
@kylechampley As you commented at some memory issue, Leap does not support sinogram base order, that only supports projection base order. As you may know, some algorithm needs this sinogram image and adapt some modification, but I have to reproduct projection images again for leap  to do back-projection which waste  lots time and memory. How about adding sinogram base back-projection option to save such time?

**Comment by kylechampley** [comment]
A few days ago I started discussion #88 for the purpose of feature requests.

**Comment by hws203** [comment]
I added my list which hoped by me to be adapted into leap package.
