### ISSUE TITLE
tau param issue with convert_modularbeam() function

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#90]
@kylechampley I used your standard cone beam script for generation this issue.

1. issue => when tau param(red 1) has been used for projection image, and the calling of convert_to_modularbeam() function shows different recon slice result.
2. no call of convert_to_modularbeam()  slice(red 2 disabled):
   <img width="695" alt="no_convert_modular" src="https://github.com/user-attachments/assets/c33f53c2-3e3a-4bc9-a421-58a89f5441df">

3. after call of convert_to_modularbeam()  slice(red 2 enabled):
    
<img width="779" alt="after_convert_modular" src="https://github.com/user-attachments/assets/57cd8d52-37da-485d-828a-b061281c63b3">

4. test script:
   
<img width="1244" alt="code_script" src="https://github.com/user-attachments/assets/c20e2555-b472-4dcc-b865-31fd86d6fe63">

5.  I think that convert_to_modularbeam()  should not change recon slice result.

**Comment by kylechampley** [comment]
Yep, that's definitely a bug.  I just fixed it and pushed changes to the [champley_dev](https://github.com/LLNL/LEAP/tree/champley_dev) branch.

Thanks for reporting this bug!

**Comment by hws203** [comment]
I have checked  your fixing, now it is cleared.
