### ISSUE TITLE
one_tube_with_two_detectors geometry config with leap package

### ISSUE THREAD

**Issue by hws203** [LLNL/LEAP#93]
@kchampley  I have some special geometry projection images which captured from the 2'nd detector for CT reconstruction.
Could you help me how to config leap geometry at such case laminography ?

![one_tube_two_detector3](https://github.com/user-attachments/assets/2f39fa2e-07a9-4019-9a24-1066853c75a3)

**Comment by kylechampley** [comment]
Looks like an interesting system, but unfortunately, I cannot help.  I only really have the time to answer questions about LEAP or fix bugs that users find.

**Comment by hws203** [comment]
I have solved this issue with detector's row vector modification for as like below geometry.

![geo](https://github.com/user-attachments/assets/ffb2bb69-dd69-44cb-9be4-1a6c1644478d)
