### ISSUE TITLE
ArgumentError in downsmapling

### ISSUE THREAD

**Issue by oooo1114** [LLNL/LEAP#94]
Hi, Kyle,
I am trying the demo for scatter correction "d31_scatter_correction.py".
But the code run into an error in line 178 when down-sampling the data.
The error information is listed below:
```
Exception has occurred: ArgumentError
argument 2: <class 'TypeError'>: array must have data type int32
  File "d31_scatter_correction.py.py", line 178, in <module>
    g_dn = leapct_LR.down_sample_projections([1,downSampleFactor,downSampleFactor],g)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: array must have data type int32
```
Any suggestions? 
Thanks.

**Comment by kylechampley** [comment]
The script runs fine for me.  Did you make any changes to it?  What version of LEAP are you running?

**Comment by oooo1114** [comment]
v1.19, I think the error may be related to my environment since you can run.

**Comment by oooo1114** [comment]
No. It might be related to other packages in the environment. Never-mind, I use torch interpolate instead. Thanks.

**Comment by kylechampley** [comment]
OK, just make sure you update the LEAP CT parameters accordingly.
